version: '3'

name: 'laravel'

services:
  database:
    container_name: laravel_database
    image: mariadb:10.6
    restart: unless-stopped
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/storage/lib:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  phpmyadmin:
    container_name: laravel_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    external_links:
      - database:db
    ports:
      - "8080:80"
  nginx:
    container_name: laravel_nginx
    image: nginx:1.23
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/storage/logs:/var/logs/nginx
  app:
    container_name: laravel_app
    build: ./app
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
    environment:
      WAIT_HOSTS: database:3306
      WAIT_AFTER: 15
